// Client-safe constants
export const SOLANA_STAKING_POOL_DATA_STORAGE_KEY = 'SOLANA_STAKING_POOL_DATA_STORAGE_KEY';
export const SOLANA_LENDING_POOL_DATA_STORAGE_KEY = 'SOLANA_LENDING_POOL_DATA_STORAGE_KEY';
