import { Intent } from '@/ai/routing/intent';
import { AgentKey, FlowMode } from '@/ai/routing/route-intent';

export type RoutingFixture = {
  name: string;
  chain: 'solana' | 'base' | 'bsc';
  userMessage: string;
  intent: Intent;
  expected: {
    agentKey: AgentKey | null;
    mode: FlowMode;
  };
  gating: {
    allowWalletConnect: boolean;
    expectsWalletConnectTool?: boolean;
  };
};

export const routingFixtures: RoutingFixture[] = [
  {
    name: 'Global yield decision routes to Recommendation',
    chain: 'solana',
    userMessage: 'Where should I earn yield right now?',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Browse lending pools stays read-only',
    chain: 'solana',
    userMessage: 'Show me USDC lending pools',
    intent: {
      domain: 'lending',
      goal: 'explore',
      decisionStrength: 'none',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'lending', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Stake execution enables tools',
    chain: 'solana',
    userMessage: 'Stake 10 SOL now',
    intent: {
      domain: 'staking',
      goal: 'execute',
      decisionStrength: 'none',
      assetScope: 'sol',
      explicitTrading: false,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.95,
    },
    expected: { agentKey: 'staking', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Trading only when explicit',
    chain: 'solana',
    userMessage: 'Swap SOL to USDC',
    intent: {
      domain: 'trading',
      goal: 'execute',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: true,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.95,
    },
    expected: { agentKey: 'trading', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Knowledge stays educational',
    chain: 'solana',
    userMessage: 'What is liquid staking?',
    intent: {
      domain: 'knowledge',
      goal: 'learn',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'knowledge', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Decision for stablecoin routes to Lending agent',
    chain: 'solana',
    userMessage: 'Best USDC yield?',
    intent: {
      domain: 'lending',
      goal: 'decide',
      decisionStrength: 'strong',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'lending', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Decision for SOL routes to Staking agent',
    chain: 'solana',
    userMessage: 'Safest SOL yield?',
    intent: {
      domain: 'staking',
      goal: 'decide',
      decisionStrength: 'strong',
      assetScope: 'sol',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'staking', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Personalization request allows wallet connect in decide mode',
    chain: 'solana',
    userMessage: 'What is the safest yield for my assets?',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: true,
      confidence: 0.85,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Explore yield does not enable wallet connect by default',
    chain: 'solana',
    userMessage: 'I want to earn yield',
    intent: {
      domain: 'yield',
      goal: 'explore',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.6,
    },
    expected: { agentKey: null, mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Base explicit trade routes to base trading',
    chain: 'base',
    userMessage: 'Swap ETH for USDC',
    intent: {
      domain: 'trading',
      goal: 'execute',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: true,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'trading', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Base portfolio transfer is execute',
    chain: 'base',
    userMessage: 'Send 0.1 ETH to 0xabc...',
    intent: {
      domain: 'portfolio',
      goal: 'execute',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'wallet', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Base explore does not enable wallet connect',
    chain: 'base',
    userMessage: 'What can I do on Base?',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.5,
    },
    expected: { agentKey: null, mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'BSC knowledge query stays knowledge',
    chain: 'bsc',
    userMessage: 'What is a BEP-20 token?',
    intent: {
      domain: 'knowledge',
      goal: 'learn',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'knowledge', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'BSC explicit trade routes to trading',
    chain: 'bsc',
    userMessage: 'Swap BNB to USDT',
    intent: {
      domain: 'trading',
      goal: 'execute',
      decisionStrength: 'none',
      assetScope: 'unknown',
      explicitTrading: true,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.85,
    },
    expected: { agentKey: 'trading', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
];
