import { Intent } from '@/ai/routing/intent';
import { AgentKey, FlowMode } from '@/ai/routing/route-intent';

export type RoutingFixture = {
  name: string;
  chain: 'solana' | 'base' | 'bsc';
  userMessage: string;
  intent: Intent;
  conversation?: {
    lastToolName?: string;
  };
  expected: {
    agentKey: AgentKey | null;
    mode: FlowMode;
  };
  gating: {
    allowWalletConnect: boolean;
    expectsWalletConnectTool?: boolean;
    hasWalletAddress?: boolean;
  };
};

export const routingFixtures: RoutingFixture[] = [
  {
    name: 'Global yield decision routes to Recommendation',
    chain: 'solana',
    userMessage: 'Where should I earn yield right now?',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'highest_yield',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Global yield decision misclassified as lending still routes to Recommendation',
    chain: 'solana',
    userMessage: 'Where should I earn yield right now?',
    intent: {
      domain: 'lending',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'highest_yield',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.7,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Safest yield unknown asset requires wallet connect',
    chain: 'solana',
    userMessage: 'Safest yield right now?',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'safest',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Safest unknown asset (no yield keyword) requires wallet connect',
    chain: 'solana',
    userMessage: 'What is the safest option right now?',
    intent: {
      domain: 'unknown',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'safest',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.75,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Imperative decide-for-me routes to Recommendation',
    chain: 'solana',
    userMessage: 'Decide for me',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'highest_yield',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.7,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Short confirmation stays on lending decide path after yield cards',
    chain: 'solana',
    userMessage: 'yes',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'lending-solana_lending_yields' },
    expected: { agentKey: 'lending', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Short confirmation stays on staking decide path after yield cards',
    chain: 'solana',
    userMessage: 'ok',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'staking-solana_liquid_staking_yields' },
    expected: { agentKey: 'staking', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Browse lending pools stays read-only',
    chain: 'solana',
    userMessage: 'Show me USDC lending pools',
    intent: {
      domain: 'lending',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'lending', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'All pools stays read-only',
    chain: 'solana',
    userMessage: 'Give me all pools',
    intent: {
      domain: 'lending',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'highest_yield',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'lending', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Out of these highest TVL stays read-only',
    chain: 'solana',
    userMessage: 'Out of these, highest TVL',
    intent: {
      domain: 'lending',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'safest',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    conversation: { lastToolName: 'lending-solana_lending_yields' },
    expected: { agentKey: 'lending', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Which has highest yield stays read-only',
    chain: 'solana',
    userMessage: 'Which has the highest yield?',
    intent: {
      domain: 'lending',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'highest_yield',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    conversation: { lastToolName: 'lending-solana_lending_yields' },
    expected: { agentKey: 'lending', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Try again resumes execute mode',
    chain: 'solana',
    userMessage: 'Try again',
    intent: {
      domain: 'lending',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'lending', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Try again resumes trading execute',
    chain: 'solana',
    userMessage: 'Try again',
    intent: {
      domain: 'trading',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: true,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'trading', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Try again resumes transfer execute',
    chain: 'solana',
    userMessage: 'Try again',
    intent: {
      domain: 'portfolio',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'wallet', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Stake execution enables tools',
    chain: 'solana',
    userMessage: 'Stake 10 SOL now',
    intent: {
      domain: 'staking',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'sol',
      explicitTrading: false,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.95,
    },
    expected: { agentKey: 'staking', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Trading only when explicit',
    chain: 'solana',
    userMessage: 'Swap SOL to USDC',
    intent: {
      domain: 'trading',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: true,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.95,
    },
    expected: { agentKey: 'trading', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Knowledge stays educational',
    chain: 'solana',
    userMessage: 'What is liquid staking?',
    intent: {
      domain: 'knowledge',
      goal: 'learn',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'knowledge', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Decision for stablecoin routes to Lending agent',
    chain: 'solana',
    userMessage: 'Best USDC yield?',
    intent: {
      domain: 'lending',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'highest_yield',
      assetScope: 'stablecoins',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'lending', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Decision for SOL routes to Staking agent',
    chain: 'solana',
    userMessage: 'Safest SOL yield?',
    intent: {
      domain: 'staking',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'safest',
      assetScope: 'sol',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'staking', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Personalization request allows wallet connect in decide mode',
    chain: 'solana',
    userMessage: 'What is the safest yield for my assets?',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'safest',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: true,
      confidence: 0.85,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Connected wallet keeps balance tools in decide mode',
    chain: 'solana',
    userMessage: 'Show my balances',
    intent: {
      domain: 'portfolio',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'wallet', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false, hasWalletAddress: true },
  },
  {
    name: 'Portfolio query allows wallet connect when disconnected',
    chain: 'solana',
    userMessage: 'what tokens do i have',
    intent: {
      domain: 'portfolio',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'wallet', mode: 'explore' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Explore yield does not enable wallet connect by default',
    chain: 'solana',
    userMessage: 'I want to earn yield',
    intent: {
      domain: 'yield',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.6,
    },
    expected: { agentKey: 'recommendation', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Imperative decide routes to Recommendation',
    chain: 'solana',
    userMessage: 'Just tell me what to do',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Confused help routes to Recommendation',
    chain: 'solana',
    userMessage: 'Help',
    intent: {
      domain: 'unknown',
      goal: 'decide',
      decisionStrength: 'weak',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.6,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Decide for me routes to Recommendation',
    chain: 'solana',
    userMessage: 'Decide for me',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.8,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Imperative portfolio optimization allows wallet connect',
    chain: 'solana',
    userMessage: 'What should I do with my wallet?',
    intent: {
      domain: 'yield',
      goal: 'decide',
      decisionStrength: 'strong',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: true,
      confidence: 0.8,
    },
    expected: { agentKey: 'recommendation', mode: 'decide' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Short follow-up keeps prior lending path',
    chain: 'solana',
    userMessage: 'yes',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'lending-solana_lending_yields' },
    expected: { agentKey: 'lending', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Short follow-up keeps prior market path',
    chain: 'solana',
    userMessage: 'ok',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'market-get-trending-tokens' },
    expected: { agentKey: 'market', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Short follow-up keeps prior token-analysis path',
    chain: 'solana',
    userMessage: 'continue',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'tokenanalysis-get-token-data' },
    expected: { agentKey: 'token-analysis', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Short follow-up keeps prior liquidity path',
    chain: 'solana',
    userMessage: 'yes',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'liquidity-get-pools' },
    expected: { agentKey: 'liquidity', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Short follow-up keeps prior knowledge path',
    chain: 'solana',
    userMessage: 'ok',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'knowledge-search_knowledge' },
    expected: { agentKey: 'knowledge', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Short follow-up keeps prior trading path (still gated unless execute)',
    chain: 'solana',
    userMessage: 'ok',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'trading-solana_trade' },
    expected: { agentKey: 'trading', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Base explicit trade routes to base trading',
    chain: 'base',
    userMessage: 'Swap ETH for USDC',
    intent: {
      domain: 'trading',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: true,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'trading', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Base portfolio transfer is execute',
    chain: 'base',
    userMessage: 'Send 0.1 ETH to 0xabc...',
    intent: {
      domain: 'portfolio',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'wallet', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'Base explore does not enable wallet connect',
    chain: 'base',
    userMessage: 'What can I do on Base?',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.5,
    },
    expected: { agentKey: null, mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Base short follow-up keeps prior trading path',
    chain: 'base',
    userMessage: 'yes',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'basetrading-trade' },
    expected: { agentKey: 'trading', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'Base help routes to Base knowledge (no execute)',
    chain: 'base',
    userMessage: 'Help me understand Base',
    intent: {
      domain: 'knowledge',
      goal: 'learn',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.7,
    },
    expected: { agentKey: 'knowledge', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'BSC knowledge query stays knowledge',
    chain: 'bsc',
    userMessage: 'What is a BEP-20 token?',
    intent: {
      domain: 'knowledge',
      goal: 'learn',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.9,
    },
    expected: { agentKey: 'knowledge', mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'BSC explicit trade routes to trading',
    chain: 'bsc',
    userMessage: 'Swap BNB to USDT',
    intent: {
      domain: 'trading',
      goal: 'execute',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: true,
      explicitExecution: true,
      needsWalletForPersonalization: false,
      confidence: 0.85,
    },
    expected: { agentKey: 'trading', mode: 'execute' },
    gating: { allowWalletConnect: true, expectsWalletConnectTool: true },
  },
  {
    name: 'BSC confused routes to discovery (no agent)',
    chain: 'bsc',
    userMessage: "I'm not sure what to do",
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.5,
    },
    expected: { agentKey: null, mode: 'explore' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
  {
    name: 'BSC short follow-up keeps prior wallet path',
    chain: 'bsc',
    userMessage: 'ok',
    intent: {
      domain: 'unknown',
      goal: 'explore',
      decisionStrength: 'none',
      objective: 'unknown',
      assetScope: 'unknown',
      explicitTrading: false,
      explicitExecution: false,
      needsWalletForPersonalization: false,
      confidence: 0.2,
    },
    conversation: { lastToolName: 'bscwallet-bsc_balance' },
    expected: { agentKey: 'wallet', mode: 'decide' },
    gating: { allowWalletConnect: false, expectsWalletConnectTool: false },
  },
];
